spring:
  application:
    name: liftly-backend
  datasource:
    url: jdbc:h2:mem:liftly_db;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  sql:
    init:
      mode: always
  flyway:
    enabled: false
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope: email, profile
          github:
            client-id: ${GITHUB_CLIENT_ID:your-github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:your-github-client-secret}
            scope: user:email, read:user

app:
  jwt:
    secret: ${JWT_SECRET:89D91DDE3A3644F9A68D25A651877CF160EBCCBFC68F3C5D08986B6D5FE03A4E}
    expiration-ms: 86400000 # 24 hours
